### ISSUE TITLE
python-flirt dependency specifier should be relaxed

### ISSUE THREAD

**Issue by mochaaP** [williballenthin/viv-utils#214]
```toml
[project.optional-dependencies]
flirt = [
    "python-flirt==0.9.0", # should be >=0.9.0
]
```

Since this isn't a build / dev dependency, this constraint should be relaxed.
Fixes dependency conflict when installing from <https://github.com/mandiant/flare-floss>.
